//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BeautyCentersProject.Models
{
    using System;
    using System.Collections.Generic;
    using System.Web;

    public partial class CentersService
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CentersService()
        {
            this.ClientRates = new HashSet<ClientRate>();
        }
    
        public int ID { get; set; }
        public int CenterID { get; set; }
        public int ServiceID { get; set; }
        public double Price { get; set; }
        public string Description { get; set; }
        public System.TimeSpan EstimatedTime { get; set; }
        public Nullable<double> TotalServicesRate { get; set; }
        public string Image { get; set; }
        public bool isDeleted { get; set; }
        public bool isSelected { get; set; }

        public int TimeMinutes { get; set; }

        public HttpPostedFileBase file { get; set; }

        public virtual BeautyCenter BeautyCenter { get; set; }
        public virtual Service Service { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ClientRate> ClientRates { get; set; }
    }
}
