//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BeautyCentersProject.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CenterAdmin
    {
        public string UserID { get; set; }
        public string NID { get; set; }
        public string CreditCard { get; set; }
        public string NiDImage { get; set; }
        public int CenterID { get; set; }
    
        public virtual AspNetUser AspNetUser { get; set; }
        public virtual BeautyCenter BeautyCenter { get; set; }
    }
}
