//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BeautyCentersProject.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class EmployeeDoService
    {
        public int ID { get; set; }
        public int ServiceID { get; set; }
        public int EmployeeID { get; set; }
        public bool IsDeleted { get; set; }
    
        public virtual Employee Employee { get; set; }
        public virtual Service Service { get; set; }
    }
}
